name: Run 5 Python Scripts on 5 Different Servers

on:
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ vào phút thứ 0
  workflow_dispatch:  # Cho phép chạy thủ công từ UI của GitHub Actions

jobs:
  run_on_server_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [x1.py, x2.py, x3.py, x4.py, x5.py]  # Chạy tất cả 5 file trên server này
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python ${{ matrix.script }}
        continue-on-error: true

  run_on_server_2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [x1.py, x2.py, x3.py, x4.py, x5.py]  # Chạy tất cả 5 file trên server này
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python ${{ matrix.script }}
        continue-on-error: true

  run_on_server_3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [x1.py, x2.py, x3.py, x4.py, x5.py]  # Chạy tất cả 5 file trên server này
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python ${{ matrix.script }}
        continue-on-error: true

  run_on_server_4:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [x1.py, x2.py, x3.py, x4.py, x5.py]  # Chạy tất cả 5 file trên server này
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python ${{ matrix.script }}
        continue-on-error: true

  run_on_server_5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [x1.py, x2.py, x3.py, x4.py, x5.py]  # Chạy tất cả 5 file trên server này
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python ${{ matrix.script }}
        continue-on-error: true
